site_name: IVEA Documentation
theme:
  name: material  # A modern UI theme

nav:
  - Home: index.md
  - IVEA Plugin Location: ivea-plugin.md
  - Random Burst Event:
      - Overview: random-burst-event.md
      - Advanced Settings: random-burst-advanced-settings.md
      - Output Results: random-burst-output-results.md
  - Stationary Event Tab:
      - Overview: stationary-event.md
      - Advanced Settings: stationary-advanced-settings.md
      - Output Results: stationary-output-results.md
  - Hotspot Area Extraction:
      - Overview: hotspot-area-extraction.md
      - Advanced Settings: hotspot-advanced-settings.md
  - ROI Multi-Measurement Plugin: roi-multi-measurement.md
  - Labeling Data:
      - Labeling New Data: labeling-new-data.md
      - Labeling ROIs in IVEA: labeling-rois.md
  - Training Using IVEA Python:
      - Main Script GUI: training-main-script.md
      - Configuration File: training-configuration-file.md
      - Environment Setup: training-environment-setup.md
      - Running and Debugging: training-running-debugging.md
  - FAQ: faq.md
  - API Reference: api.md
